language: node_js
node_js:
  - 14
sudo: required

services:
  - docker

before_install:
  - docker build -t react-docker-app -f Dockerfile.dev .

script:
  - docker run react-docker-app npm run test -- --watchAll=false
