language: node_js
node_js:
  - 14


services:
  - docker

before_install:
  - docker build -t react-docker-app -f Dockerfile.dev .

script:
  - docker run react-docker-app npm run test -- --watchAll=false
  
deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"  
  app: "react-app-deployment"
  env:  "Reactappdeployment-env"
  bucket_name: "elasticbeanstalk-us-east-2-640481902462"
  bucket_path: "react-app-deployment"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
